Changin to new codebase
hoonsubin/energywise-homepage pull request #16
Opened 2023-07-02 16:17 UTC by energywis3

Changing to a new code base

2023-07-02 17:02 UTC, energywis3 commented
Deleted the previous files and folders

2023-07-03 10:42 UTC, hoonsubin requested changes

2023-07-03 10:42 UTC, hoonsubin commented on src/components/services/Services.jsx
> +  const [selectedItemId, setSelectedItemId] = useState(null);
This value is never used. What is the purpose?

2023-07-03 10:42 UTC, hoonsubin commented on src/components/top/TopHeader.jsx
> +  const [isTranslated, setIsTranslated] = useState(false);
This value is never set. What is the purpose? Please remove unused vars

2023-07-03 11:02 UTC, merged