Update Hero.tsx
hoonsubin/energywise-homepage pull request #8
Opened 2023-05-24 13:46 UTC by energywis3

const validateEmail = () => {
    const emailInput = document.getElementById('email');
    const email = emailInput.value.trim();
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

    if (!emailRegex.test(email)) {
      alert('Please enter a valid email address.');
      return false;
    }

the email is still calling for invalid inputs after error message

2023-05-26 10:24 UTC, hoonsubin requested changes

2023-05-26 10:24 UTC, hoonsubin commented on src/templates/Hero.tsx
> +  const validateEmail = () => {
You should make this into a `useCallback` function

2023-05-26 10:24 UTC, hoonsubin commented on src/templates/Hero.tsx
> +              <input
For the text input, use can use `onChange` property to pass on the input content. Store the user input string into a `useState` variable that the button click function will look from

2023-05-27 20:46 UTC, energywis3 commented
mail function has been fixed, updated the code.

2023-06-02 09:36 UTC, hoonsubin commented
This PR was opened for a while. What is the progress?

2023-06-17 08:16 UTC, closed without merging

2024-04-30 02:30 UTC, masa2el commented
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
ikeom-je, @hayatoVTA, @crashquentin, @tawseefnabi, @Multi-Nick, @mortezashojaei, @ragmha, @shontauro, @bransorem, @narendra751, @Loulou-06, @MatejLach, @junekomori, @da-bao-jian, @kazuki-hanai, @droiddikshit, @ZRDKPoWeR, @tuchg, @dabo-yang, @fionnachan, @ShaunLWM, @lotgyero, @zhoulvyuan, @ChachiTheGhost, @Yhozen, @pronebel, @kwameboame, @io12, @elvirafitriani, @Stephen-Song, @anton-karlovskiy, @marcoaubr, @blackvitriol, @ethan1sung, @ganja24680, @Rackar, @slim-patchy, @andyGallagher, @aakashditya, @elvisisvan, @lionbllack, @selcukvardar, @tan-zixuan, @Merlin0126, @davidmichaelhuber, @lewandy, @plommon, @Devorein, @dacoffey, @zhouop0sumukhah, @ikeom-je, @Aniket-Engg, @metaspartan, @davidmichaelhuber, @starkmerv, @gold502, @CHTONGY, @phuocnguyen7729, @coryjo, @Cassy2202, @pronebel, @elvisisvan, @lewandy, @ShaunLWM, @kwameboame, @alejoasotelo, @selcukvardar, @mortezashojaei, @priyakkum, @aakashditya, @spicy-tomato, @tan-zixuan, @hayatoVTA, @sedat1943, @wujunze, @loredanacirstea, @fionnachan, @kazuki-hanai, @akhileshthite, @dacoffey, @elvirafitriani, @Stephen-Song, @Yhozen, @dkodnik, @anyinfa, @yoshiki495, @zhoulvyuan, @CriDos, @Soloer, @semamainco, @raymondlei90s, @westonnelson, @devincapriola, @yoandresaav, @pariya-tavangar, @dodo920306, @guolan, @blackvitriol, @onepisYajettang2019, @CHTONGY, @spicy-tomato, @0xdwong, @alan10332000, @j5465, @hayatoVTA, @Aniket-Engg, @andydptyo, @anistark, @sedat1943, @cerveeza77, @blackvitriol, @henrytirla, @Boyquotes, @masterboy2002, @bransorem, @CriDos, @Rackar, @semamainco, @loredanacirstea, @sivenLee, @akhileshthite, @georgerobescu, @ErezLevip, @pariya-tavangar, @suyanlong, @Dash-n1, @devincapriola, @crashquentin, @faisalrahman36, @metaspartan, @tuchg, @Multi-Nick, @myzykj, @ikeom-je, @starkmerv, @Julybui199x, @onepisYa, @yoandresaav, @andyGallagher, @anton-karlovskiy, @SOLT16376, @destrat18, @Merlin0126, @dkodnik, @slim-patchy, @coryjo, @selcukvardar, @dwallach1pleiadesian, @Artificialimbecile, @yoandresaav, @RusseII, @dodo920306, @narendra751, @andydptyo, @alejoasotelo, @lewandy, @junekomori, @Julybui199x, @Dash-n1, @blackvitriol, @plommon, @CHTONGY, @masterboy2002, @fionnachan, @tawseefnabi, @priyakkum, @tan-zixuan, @guolan, @jpanachida, @ragmha, @semamainco, @marcoaubr, @yoshiki495, @anyinfa, @ShaunLWM, @davidmichaelhuber, @andyGallagher, @Loulou-06, @RuiXi-Verilog, @alan10332000, @pariya-tavangar, @Yhozen, @Rami-Majdoub, @k3kiroashi, @evebyte, @jacklam718, @sumukhah, @ikeom-je, @asdwsxzc123, @westonnelson, @mortezashojaei, @kwameboame, @raymondlei90s, @dkodnik, @wujunze, @lionbllack, @barisateszhoulvyuan, @dwallach1, @m-ochi, @onepisYa, @io12, @crashquentin, @selcukvardar, @dabo-yang, @Cassy2202, @Rackar, @elvirafitriani, @bransorem, @Zakiahzamy, @harry-oestreicher, @0292568684, @skiran017, @lotgyero, @jaypaik, @aeharvlee, @Merlin0126, @devincapriola, @ArslanYM, @Puskas1, @ViacheslavK, @brandnewx, @ChachiTheGhost, @anistark, @Enriweest0723, @pronebel, @aakashditya, @tuchg, @SOLT16376, @0xdwong, @jettang2019, @Devorein, @MatejLach, @ZRDKPoWeR, @espumita, @dacoffey, @j5465, @xiaohuoni, @da-bao-jian, @CriDos, @zhouop0, @myzykj, @spicy-tomato, @yutingzhao1991, @kazuki-hanai, @loredanacirstea, @henrytirla